
if [[ -d ~/.oh-my-zsh ]]
then
  export ZSH=/Users/david/.oh-my-zsh
  ZSH_THEME="robbyrussell"
  DISABLE_AUTO_UPDATE="true"

  # Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
  # Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
  # Example format: plugins=(rails git textmate ruby lighthouse)
  # Add wisely, as too many plugins slow down shell startup.
  plugins=(
    git
  )

  source $ZSH/oh-my-zsh.sh
fi

if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

alias d='docker $*'
alias dc='docker-compose $*'
alias bx='bundle exec $*'
alias ap='ansible-playbook $*'