
if [[ -d ~/.oh-my-zsh ]]
then
  export ZSH=/Users/david/.oh-my-zsh
  ZSH_THEME="robbyrussell"
  DISABLE_AUTO_UPDATE="true"

  # Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
  # Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
  # Example format: plugins=(rails git textmate ruby lighthouse)
  # Add wisely, as too many plugins slow down shell startup.
  plugins=(
    git
  )

  source $ZSH/oh-my-zsh.sh
fi

export PATH=./node_modules/.bin:./bin:$HOME/bin:$PATH

if [[ -a ~/.localrc ]]
then
  source ~/.localrc
fi

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

alias d='docker $*'
alias dc='docker-compose $*'
alias bx='bundle exec $*'
alias ap='ansible-playbook $*'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/david/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/david/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/david/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/david/google-cloud-sdk/completion.zsh.inc'; fi
